name: Sync luci from LEDE

on:
  schedule:
    - cron: '0 6 * * *'  # 每天凌晨6点同步
  workflow_dispatch:  # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your forked repo
        uses: actions/checkout@v2
        with:
          repository: tonyzzt001/Tony_Luci  # 替换为你的用户名和仓库名
          ref: openwrt-23.05  # 替换为你的默认分支名称

      - name: Set up Git
        run: |
          git config --global user.email "tony_zzt@sina.com"
          git config --global user.name "tonyzzt001"

      - name: Add upstream repository
        run: git remote add upstream https://github.com/coolsnowwolf/luci.git

      - name: Fetch upstream changes for openwrt-23.05
        run: |
          git fetch upstream
          git checkout openwrt-23.05
          git merge upstream/openwrt-23.05 --allow-unrelated-histories -m "Merge from upstream openwrt-23.05"
          git push origin openwrt-23.05

      - name: Fetch upstream changes for master
        run: |
          git fetch upstream
          git checkout master
          git merge upstream/master --allow-unrelated-histories -m "Merge from upstream master" || true  # 尝试合并，如果有冲突则继续执行
          git push origin master || true  # 如果推送失败，继续执行后续步骤

      - name: Pull latest changes if push failed
        run: |
          git pull --rebase upstream master || echo "No changes to pull"
          git push origin master
