name: Sync with upstream

on:
  schedule:
    - cron: '0 6 * * *'  # 每天凌晨6点同步

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your forked repo
        uses: actions/checkout@v2
        with:
          repository: tonyzzt001/Tony_Luci  # 替换为你的用户名和仓库名
          ref: main  # 替换为你的默认分支名称

      - name: Add upstream repository
        run: git remote add upstream https://github.com/coolsnowwolf/luci.git  # 修正为仓库地址

      - name: Fetch upstream changes
        run: git fetch upstream

      - name: Merge upstream changes
        run: |
          git checkout main  # 确保在正确的分支上
          git merge upstream/openwrt-23.05 -m "Merge from upstream"  # 使用正确的 upstream 分支
          git push origin main
