name: Sync luci from LEDE

on:
  workflow_dispatch:  # 允许手动触发
  schedule:
    - cron: '0 6 * * *'  # 每天凌晨6点同步

jobs:
  sync_openwrt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your forked repo
        uses: actions/checkout@v2
        with:
          repository: tonyzzt001/Tony_Luci  # 替换为你的用户名和仓库名
          ref: openwrt-23.05  # 指定要同步的分支

      - name: Add upstream repository
        run: git remote add upstream https://github.com/coolsnowwolf/luci.git

      - name: Fetch upstream changes
        run: git fetch upstream

      - name: Merge upstream changes
        run: |
          git checkout openwrt-23.05
          git merge upstream/openwrt-23.05 --allow-unrelated-histories -m "Merge from upstream"
          git push origin openwrt-23.05

  sync_master:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your forked repo
        uses: actions/checkout@v2
        with:
          repository: tonyzzt001/Tony_Luci  # 替换为你的用户名和仓库名
          ref: master  # 指定要同步的分支

      - name: Add upstream repository
        run: git remote add upstream https://github.com/coolsnowwolf/luci.git

      - name: Fetch upstream changes
        run: git fetch upstream

      - name: Merge upstream changes
        run: |
          git checkout master
          git merge upstream/master --allow-unrelated-histories -m "Merge from upstream"
          git push origin master
